### ISSUE TITLE
I wonder if we can adopt the repository 🤔

### ISSUE THREAD

**Issue by devlikepro** [morning-bird/n8n-nodes-waha#3]
First of all, WOW :+1: 
We had a plan to start integrating the project with n8n/chatwoot/typebot this month, but found you already have done a huge work, thank you!

We'd love to get the repo under https://github.com/devlikeapro/ org, so people can use and we could develop and update to the latest version as well :pray: 

So may questions are:
1. Could we move https://github.com/morning-bird/n8n-nodes-waha to https://github.com/devlikeapro/ ?
2. Can we transfer npm module `n8n-nodes-waha` to `devlikeapro` user? (https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account)

If not - that's totally fine, we'll fork it and create a new npm package for that, no worries!
Thank you for your work, it's amazing job! :bow: You're the best :1st_place_medal:

**Comment by morning-bird** [comment]
Hi, of course we can do that. Let me check what I need to move the package first. @devlikepro

**Comment by devlikepro** [comment]
@morning-bird that's would be awesome! 

Do you have a discord so we can talk about this? 
Send a nickname pls :pray: waha@devlike.pro

For github prolbaby we'll just fork, that's totally fine

**Comment by devlikepro** [comment]
Here you go! All API is now available in n8n node
![image](https://github.com/user-attachments/assets/65769740-2593-42f7-8308-20126cc8872d)

https://github.com/devlikeapro/n8n-nodes-waha
```
@devlikeapro/n8n-nodes-waha
```


IDK why, but 1.56.2 n8n doesn't install the package properly, so kindly use n8n>1.57.0
